name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
      # packages: write
      # id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      
    - uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
        cache: true

    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/setup-qemu-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      with:
        context: .
        file: ./build/minecraft-server-wrapper/Dockerfile
        platforms: linux/amd64
        push: true
        sbom: true
        provenance: true
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/minecraft-server-wrapper:latest
          ${{ vars.DOCKERHUB_USERNAME }}/minecraft-server-wrapper:${{ github.ref_name }}

    - uses: docker/build-push-action@v6
      with:
        context: .
        file: ./build/minecraft-server-center/Dockerfile
        platforms: linux/amd64
        push: true
        sbom: true
        provenance: true
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/minecraft-server-center:latest
          ${{ vars.DOCKERHUB_USERNAME }}/minecraft-server-center:${{ github.ref_name }}
